--- !ditz.rubyforge.org,2008-03-06/project 
name: cupage
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: cupage
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.5.0
  status: :unreleased
  release_time: 
  log_events: 
  - - 2010-01-28 10:09:41.875818 Z
    - James Rowe <jnrowe@gmail.com>
    - created
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: bluesky
  status: :unreleased
  release_time: 
  log_events: 
  - - 2010-06-08 18:42:33.411733 Z
    - James Rowe <jnrowe@gmail.com>
    - created
    - Things that would be nice to have... at some point.
